#!/bin/bash

# Check 2 params
if [ "$#" -ne 1 ]; then
	echo "Usage: ./compile.sh <output_file>"
	exit 1
fi

g++ bitboard.cpp *.cpp -mavx2 -mbmi2 -mbmi -mlzcnt -mpopcnt -O3 -o $1
x86_64-w64-mingw32-g++ -O3 -mavx2 -mbmi -mbmi2 -mlzcnt -mpopcnt -static -o win_pzchessbot.exe *.cpp -DWINDOWS
