#!/bin/bash

# Check 2 params
if [ "$#" -ne 1 ]; then
	echo "Usage: ./compile.sh <output_file>"
	exit 1
fi

g++ bitboard.cpp eval.cpp main.cpp movegen.cpp search.cpp ttable.cpp -mavx2 -mbmi2 -mbmi -mlzcnt -mpopcnt -m64 -g -o $1