name: Searching checks

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    perfts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install boost
              uses: MarkusJx/install-boost@v2.4.1
              id: install-boost
              with:
                  boost_version: 1.81.0
                  boost_install_dir: /home/runner/boost
                  toolset: gcc
                  arch: aarch64
            - name: compile engine
              run: cd engine && g++ *.cpp -O3 -mbmi -m64 -mlzcnt
            - name: compile test binary
              run: cd test && g++ perfts.cpp ../engine/!(main).cpp -O3 -mbmi -m64 -mlzcnt -o perfts.out -DPERFT
            - name: test
              run: ./test/perfts
    positions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: cd test && g++ search.cpp ../engine/!(main).cpp -O3 -mbmi -m64 -mlzcnt -o search.out
            - name: test
              run: ./test/search
