name: Searching checks

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    perfts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: bash -c "g++ test/perfts.cpp $(find engine/!(main).cpp | tr '\n' ' ') -O3 -mbmi -m64 -mlzcnt -o test/perfts.out -DPERFT"
            - name: test
              run: ./test/perfts.out
    positions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: bash -c "g++ test/search.cpp $(find engine/!(main).cpp | tr '\n' ' ') -O3 -mbmi -m64 -mlzcnt -o test/search.out -DPERFT"
            - name: test
              run: ./test/search.out
