name: Searching checks

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    perfts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: cd test && g++ perfts.cpp ../engine/bitboard.cpp ../engine/moves.cpp ../engine/search.cpp -O3 -mbmi -m64 -mlzcnt -fPIC -DPERFT -o perfts.out
            - name: test
              run: ./test/perfts.out
    positions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: cd test && g++ search.cpp ../engine/bitboard.cpp ../engine/moves.cpp ../engine/search.cpp -O3 -mbmi -m64 -mlzcnt -fPIC -o search.out
            - name: test
              run: ./test/search.out
